polls/config/urls.py
'''
include는 다른 urls.py 파일을 참조할 수 있도록 합니다.
만약 /polls/list/라는 주소로 접속하면 polls/까지는 잘라내고 list/부분만
polls/urls.py 에서 찾습니다.
'''


from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

]

polls/polls/urls.py
'''
    path 함수는 path(route, view, kwargs, name)형태로 호출한다.
    주소 , 호출할 뷰, 뷰에 전달할 값, route의 이름 순서이다.
    name은 config/urls.py 파일에 연결해야 동작한다.
'''

from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.result, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # /polls/5/vote 식.  <>는 변수를 의미한다.

]

polls/polls/models.py
'''
쉽게 테이블과 컬럼을 만든다고 생각한다.
질문 모델 -> 질문 텍스트와, 날짜
선택 모델 -> 질문(Question에 소속되는 외래키) , 선택 텍스트, 투표

모델을 완성한 후
config/setting.py 에서 INSTALLED_APPS 윗줄에 추가한 후
python manage.py makemigrations polls 로 데이터 베이스에 적용시켜 준다.
'''

import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):  # 객체를 출력 할 때 나타날 내용.
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/polls/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse
from django.template import loader
from .models import  Question

from django.http import  Http404


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.question_text for q in latest_question_list])
    context = {'latest_question_list': latest_question_list }
    return render(request, 'polls/index.html', context)
    # return HttpResponse(output)


def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id)
    # return HttpResponse("You're looking at question %s." % question_id)
    return render(request, 'polls/detail.html', {'question': question})


def result(request, question_id):
    response = "you're looking at the result fo question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ question }}
    <h1> {{question.question_text}}</h1>
    {% if error_message %} <p><strong></strong></p> {%endif%}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter }}" value="{{ choice.id }}" >
        <label for ="choice{{forloop.counter }}">{{choice.choice_text }} </label><br>
    {% endfor }
    <input type="submit" value="Vote">
    </form>


<!--    <ul>-->
<!--        {% for choice in question.choice_set.all %}-->
<!--        <li> {{choice.choice_text }}</li>-->
<!--        {% endfor }-->

<!--    </ul>-->
</body>
</html>

polls/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li> <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <p> No polls are available. </p>
{% endif %}
</body>
</html>